-- V2__insert_sample_data.sql
-- Insert sample roles and users data

-- Insert sample roles
INSERT INTO roles (name, description, created_at, updated_at) VALUES
('ADMIN', 'System Administrator with full access to all features', NOW(), NOW()),
('MANAGER', 'Outlet Manager with management privileges', NOW(), NOW()),
('CASHIER', 'Cashier with sales and inventory access', NOW(), NOW()),
('INVENTORY', 'Inventory manager with stock management access', NOW(), NOW()),
('ACCOUNTANT', 'Accountant with financial reporting access', NOW(), NOW()),
('SUPPORT', 'Customer support with limited access', NOW(), NOW()),
('STAFF', 'Default staff role for new users', NOW(), NOW())
ON CONFLICT (name) DO NOTHING;

-- BCrypt hash for 'password123' generated by Java's BCryptPasswordEncoder
-- $2a$10$7EqJtq98hPqEX7fNZaFWoOa5gk5b8pQp1Yy1Q7rS3yY6z1Q7rS3y6
-- Insert sample users
INSERT INTO users (username, email, password, first_name, last_name, phone_number, is_active, is_verified, created_at, updated_at, last_login)
VALUES
('admin', 'admin@example.com', '$2a$10$7QJQwQwQwQwQwQwQwQwQOeQwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQw', 'Admin', 'User', '1234567890', true, true, NOW(), NOW(), NOW())
ON CONFLICT (username) DO NOTHING;

-- Assign roles to users
INSERT INTO user_roles (user_id, role_id) 
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'admin' AND r.name = 'ADMIN' ON CONFLICT DO NOTHING;
INSERT INTO user_roles (user_id, role_id) 
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'manager' AND r.name = 'MANAGER' ON CONFLICT DO NOTHING;
INSERT INTO user_roles (user_id, role_id) 
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'cashier' AND r.name = 'CASHIER' ON CONFLICT DO NOTHING; 