server:
  port: 8087
  servlet:
    context-path: /api/recipe

spring:
  application:
    name: recipe-service
  
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/smartoutlet_recipe?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:smartoutlet_user}
    password: ${MYSQL_PASSWORD:smartoutlet_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# Security
security:
  jwt:
    secret: ${JWT_SECRET:SmartOutletJWTSecretKeyForDevelopment2024!}
    expiration: ${JWT_EXPIRATION:86400000}

# Logging
logging:
  level:
    com.smartoutlet.recipe: ${LOG_LEVEL:INFO}
    org.springframework.security: DEBUG
    org.hibernate.SQL: ${SHOW_SQL:false}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SHOW_SQL:false}

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Business Configuration
recipe:
  consumption:
    default-wastage-percentage: 5.0  # Default wastage factor for raw materials
    batch-size-multiplier: 1.1       # Safety buffer for batch calculations
  forecasting:
    default-days-ahead: 30           # Default forecast period
    historical-data-months: 6        # Months of historical data to consider
  vendor:
    lead-time-days: 7                # Default vendor lead time
    reorder-buffer-days: 3           # Buffer days for reorder calculations
  costing:
    include-wastage: true            # Include wastage in cost calculations
    overhead-percentage: 15.0        # Manufacturing overhead percentage